### ISSUE TITLE
Correct way to use this?

### ISSUE THREAD

**Issue by trybguet-dev** [Powie/plesk_mailcert#4]
I'm very new to plesk and it might be a very stupid question, but: how to use this correctly? As I can see, this is not a plesk extension. To which directory should I copy these files?

What is the recommended cronjob for this script?

Thank you in advance!

**Comment by BoiseComputer** [comment]
I have a little more detailed instructions for the cron job on my version of the script.
https://github.com/BoiseComputer/plesk_mailcert
Not all of the options I have in mine are available on Powie's version, so, you will have to adjust the settings in the cron job if you have his installed.

**Comment by trybguet-dev** [comment]
This worked like a charm, you saved my evening :D thank you very much!

Oh, just one question:

I made the cron run exactly 15 minutes after letsencrypt certificates renew.. this should be fine, aye?
